In [1]:
from pathlib import Path
import pandas as pd

# Project root
PROJECT_ROOT = Path.cwd().parent

# Original Amazon dataset
DATA_ROOT = PROJECT_ROOT / "student_resource"

print("Project root:", PROJECT_ROOT)
print("Student resource:", DATA_ROOT)
print("Exists:", DATA_ROOT.exists())

Project root: c:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026
Student resource: c:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026\student_resource
Exists: True

In [15]:
from pathlib import Path
import pandas as pd

# Find project root by looking for student_resource
current = Path.cwd()

if (current / "student_resource").exists():
    PROJECT_ROOT = current
elif (current.parent / "student_resource").exists():
    PROJECT_ROOT = current.parent
else:
    raise FileNotFoundError(
        "Could not find student_resource folder. "
        f"Checked: {current} and {current.parent}"
    )

DATA_ROOT = PROJECT_ROOT / "student_resource"

print("Project root:", PROJECT_ROOT)
print("Student resource:", DATA_ROOT)
print("Exists:", DATA_ROOT.exists())

Project root: c:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026
Student resource: c:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026\student_resource
Exists: True

In [2]:
tsv_files = sorted(DATA_ROOT.rglob("*.tsv"))

print(f"Found {len(tsv_files)} TSV files:\n")

for file in tsv_files:
    print(file.relative_to(DATA_ROOT))

Found 7 TSV files:

dataset\test\test_source1.tsv
dataset\test\test_source2.tsv
dataset\test\test_source3.tsv
dataset\train\train_ground_truth.tsv
dataset\train\train_source1.tsv
dataset\train\train_source2.tsv
dataset\train\train_source3.tsv

In [3]:
for file in tsv_files:
    print("\n" + "=" * 80)
    print("FILE:", file.relative_to(DATA_ROOT))

    df_sample = pd.read_csv(
        file,
        sep="\t",
        nrows=5
    )

    print("Columns:", list(df_sample.columns))
    print("Sample shape:", df_sample.shape)
    display(df_sample.head())

================================================================================
FILE: dataset\test\test_source1.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Sample shape: (5, 4)

,entity_id,business_name,business_address,country
0,S1-714132312,Zephay Labs Inc,"2621 Cotten Road, Tyler, TX",US
1,S1-106407869,Vision Partners Corp,"IA, Iowa City, 1064 Newton Rd, Unit 11",US
2,S1-156285671,<< Team Ecole,"175 Boulevard du Président Franklin Roosevelt,...",France
3,S1-689823050,Red Perfect Trading,"Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...",India
4,S1-921369899,ZNB Club SARL,"Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...",France

================================================================================
FILE: dataset\test\test_source2.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Sample shape: (5, 4)

,entity_id,business_name,business_address,country
0,S2-192345572,Brahma Infosoft,"COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...",India
1,S2-566025912,Marina Ecole France Sarl,"63 R. DE DIEPPE, LILLE, Hauts-de-France",France
2,S2-158121477,SCI Ptit Àmicale,"18 RUE JEN ZAY, Dunkerque, Nord",France
3,S2-89663826,Apex Summit,"67 KENTUCKY ST, SALYERSVILLE, KY",US
4,S2-884102769,Fresh Truist,"8264 FILLY COURT, ROANOKE COUNTY, VA",US

================================================================================
FILE: dataset\test\test_source3.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Sample shape: (5, 4)

,entity_id,business_name,business_address,country
0,S3-462677478,मॉडर्न फाइनेंस,"No 10 Enkay Square, 448A, Udyog Vihar Phase V,...",India
1,S3-374810425,Shri Sai Infratech Co,"3/115, East Delhi, DL",India
2,S3-198586129,Fractales Amis Groupe S.A.S,"23 Rue Icmre, La Teste-de-buch, Gironde",France
3,S3-10300249,Shri Supreme Consulting Private (Limited),"H.no 910 A 3503, Mumbai, महाराष्ट्र",India
4,S3-604980231,Prime Realty Ventures Public Limited,"G.t. Karnal Road, Industrial Area, New Delhi, ...",India

================================================================================
FILE: dataset\train\train_ground_truth.tsv
Columns: ['source1_entity_id', 'matched_entity_ids']
Sample shape: (5, 2)

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

================================================================================
FILE: dataset\train\train_source1.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Sample shape: (5, 4)

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

================================================================================
FILE: dataset\train\train_source2.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Sample shape: (5, 4)

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

================================================================================
FILE: dataset\train\train_source3.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']
Sample shape: (5, 4)

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

In [4]:
source_files = {}
ground_truth_file = None

for file in tsv_files:
    columns = set(
        pd.read_csv(file, sep="\t", nrows=0).columns
    )

    if {
        "entity_id",
        "business_name",
        "business_address",
        "country"
    }.issubset(columns):
        source_files[file.name] = file

    elif {
        "source1_entity_id",
        "matched_entity_ids"
    }.issubset(columns):
        ground_truth_file = file

print("SOURCE FILES")
for name, path in source_files.items():
    print(name, "->", path)

print("\nGROUND TRUTH")
print(ground_truth_file)

SOURCE FILES
test_source1.tsv -> c:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026\student_resource\dataset\test\test_source1.tsv
test_source2.tsv -> c:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026\student_resource\dataset\test\test_source2.tsv
test_source3.tsv -> c:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026\student_resource\dataset\test\test_source3.tsv
train_source1.tsv -> c:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026\student_resource\dataset\train\train_source1.tsv
train_source2.tsv -> c:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026\student_resource\dataset\train\train_source2.tsv
train_source3.tsv -> c:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026\student_resource\dataset\train\train_source3.tsv

GROUND TRUTH
c:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026\student_resource\dataset\train\train_ground_truth.tsv

In [5]:
for name, path in source_files.items():
    print(name, "->", path.parent.relative_to(DATA_ROOT))

test_source1.tsv -> dataset\test
test_source2.tsv -> dataset\test
test_source3.tsv -> dataset\test
train_source1.tsv -> dataset\train
train_source2.tsv -> dataset\train
train_source3.tsv -> dataset\train

In [6]:
sources = {}

for name, path in source_files.items():
    print(f"Loading {name} ...")

    sources[name] = pd.read_csv(
        path,
        sep="\t"
    )

    print("  Shape:", sources[name].shape)

print("\nLoaded datasets:", len(sources))

Loading test_source1.tsv ...
  Shape: (1732544, 4)
Loading test_source2.tsv ...
  Shape: (4887273, 4)
Loading test_source3.tsv ...
  Shape: (5082316, 4)
Loading train_source1.tsv ...
  Shape: (2206821, 4)
Loading train_source2.tsv ...
  Shape: (5034616, 4)
Loading train_source3.tsv ...
  Shape: (5285603, 4)

Loaded datasets: 6

In [9]:
for name, df in sources.items():

    print("\n" + "=" * 80)
    print(name)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))

    print("\nColumns:")
    print(list(df.columns))

    print("\nMissing values:")
    print(df.isna().sum())

    print("\nDuplicate rows:", df.duplicated().sum())

================================================================================
test_source1.tsv
Rows: 1732544
Columns: 4

Columns:
['entity_id', 'business_name', 'business_address', 'country']

Missing values:
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

Duplicate rows: 0

================================================================================
test_source2.tsv
Rows: 4887273
Columns: 4

Columns:
['entity_id', 'business_name', 'business_address', 'country']

Missing values:
entity_id                0
business_name           46
business_address    129408
country                  0
dtype: int64

Duplicate rows: 0

================================================================================
test_source3.tsv
Rows: 5082316
Columns: 4

Columns:
['entity_id', 'business_name', 'business_address', 'country']

Missing values:
entity_id                0
business_name           59
business_address    136098
country                  0
dtype: int64

Duplicate rows: 0

================================================================================
train_source1.tsv
Rows: 2206821
Columns: 4

Columns:
['entity_id', 'business_name', 'business_address', 'country']

Missing values:
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

Duplicate rows: 0

================================================================================
train_source2.tsv
Rows: 5034616
Columns: 4

Columns:
['entity_id', 'business_name', 'business_address', 'country']

Missing values:
entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64

Duplicate rows: 0

================================================================================
train_source3.tsv
Rows: 5285603
Columns: 4

Columns:
['entity_id', 'business_name', 'business_address', 'country']

Missing values:
entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

Duplicate rows: 0

In [10]:
ground_truth = pd.read_csv(
    ground_truth_file,
    sep="\t"
)

print("Ground truth shape:", ground_truth.shape)

display(ground_truth.head(10))

Ground truth shape: (2206821, 2)

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [11]:
print(ground_truth.columns.tolist())

['source1_entity_id', 'matched_entity_ids']

In [12]:
def count_matches(value):
    if pd.isna(value) or str(value).strip() == "":
        return 0

    return len(
        [
            x.strip()
            for x in str(value).split(",")
            if x.strip()
        ]
    )


ground_truth["match_count"] = (
    ground_truth["matched_entity_ids"]
    .apply(count_matches)
)

print(
    ground_truth["match_count"]
    .value_counts()
    .sort_index()
)

match_count
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

In [13]:
print("\nMatch distribution:")

print(
    ground_truth["match_count"]
    .value_counts()
    .sort_index()
)

print("\nPercentage:")

print(
    (
        ground_truth["match_count"]
        .value_counts(normalize=True)
        .sort_index()
        * 100
    ).round(2)
)

Match distribution:
match_count
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

Percentage:
match_count
0      5.58
1      5.40
2     17.00
3     24.05
4     21.94
5     14.59
6      7.47
7      2.90
8      0.85
9      0.19
10     0.02
11     0.00
Name: proportion, dtype: float64

In [14]:
for name, df in sources.items():

    print("\n" + "=" * 80)
    print(name)

    display(
        df[
            [
                "entity_id",
                "business_name",
                "business_address",
                "country"
            ]
        ].head(10)
    )

================================================================================
test_source1.tsv

,entity_id,business_name,business_address,country
0,S1-714132312,Zephay Labs Inc,"2621 Cotten Road, Tyler, TX",US
1,S1-106407869,Vision Partners Corp,"IA, Iowa City, 1064 Newton Rd, Unit 11",US
2,S1-156285671,<< Team Ecole,"175 Boulevard du Président Franklin Roosevelt,...",France
3,S1-689823050,Red Perfect Trading,"Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...",India
4,S1-921369899,ZNB Club SARL,"Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...",France
5,S1-481669221,Nandlal Kisan LLP,"D-61 Ifs Apartmentmayur Vihar I, New Delhi, Ea...",India
6,S1-909865979,Cure Seafood,"1325 Brooklyn Walk, Issaquah, WA",US
7,S1-280204013,Om Constructions Pvt Ltd,"Karauli, Rajasthan, Karauli, Pani Ki Tanki Ke ...",India
8,S1-742053041,Roongta Sangh,"Bhubaneswar, Sub Plot No.-L6/29, Mahodadhi Bha...",India
9,S1-913506265,Thermal & Fils SASU,"20 Rue Parmentier, Dunkerque, Hauts-de-France",France

================================================================================
test_source2.tsv

,entity_id,business_name,business_address,country
0,S2-192345572,Brahma Infosoft,"COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...",India
1,S2-566025912,Marina Ecole France Sarl,"63 R. DE DIEPPE, LILLE, Hauts-de-France",France
2,S2-158121477,SCI Ptit Àmicale,"18 RUE JEN ZAY, Dunkerque, Nord",France
3,S2-89663826,Apex Summit,"67 KENTUCKY ST, SALYERSVILLE, KY",US
4,S2-884102769,Fresh Truist,"8264 FILLY COURT, ROANOKE COUNTY, VA",US
5,S2-910351373,PVT. INDUSTRIES PMB LEASING LIMITED,"SURAT, OFFICE NO. 03038, TRADE HOUSE, NEAR RUS...",India
6,S2-229677112,Clm Agro [Limited],"G-B3/5, T V INDUSTRIAL ESTATE 248/A, S K AHIRE...",India
7,S2-770341988,sci ligue ici parents,"NO. 5 ALLÉE DES HÊTRES, Pornic, Loire-Atlantique",France
8,S2-375151053,A DIAMOND SHORT LLC,"126-B New Line Road, MORRISTOWN, TN",US
9,S2-701289183,Fanni's Dmaigesostcis,"1200 HWY 1187, CROWLEY, TX",US

================================================================================
test_source3.tsv

,entity_id,business_name,business_address,country
0,S3-462677478,मॉडर्न फाइनेंस,"No 10 Enkay Square, 448A, Udyog Vihar Phase V,...",India
1,S3-374810425,Shri Sai Infratech Co,"3/115, East Delhi, DL",India
2,S3-198586129,Fractales Amis Groupe S.A.S,"23 Rue Icmre, La Teste-de-buch, Gironde",France
3,S3-10300249,Shri Supreme Consulting Private (Limited),"H.no 910 A 3503, Mumbai, महाराष्ट्र",India
4,S3-604980231,Prime Realty Ventures Public Limited,"G.t. Karnal Road, Industrial Area, New Delhi, ...",India
5,S3-577972146,Perfect Investments Private,"Plot No.99, Flat No.201, Sri Dhama Apts., Road...",India
6,S3-150632472,Pace Mfa PC,"2132 Thomas Run Road, Bel Air, Maryland",US
7,S3-184785497,ஈஸ்டர்ன் கன்சல்டன்சி பிரைவேட் லிமிடெட்,"1410 Sri Mahalakshmi Mandiar 59, Justice Rathi...",India
8,S3-536202929,PU Pvt. Ltd. Services,"TG, Plot No-25, Hyderabad, Qutubullapur, 26, 2...",India
9,S3-560657213,Sun पावर Provision,"143-Alig Flats Rajouri Garden, New Delhi, West...",India

================================================================================
train_source1.tsv

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India
5,S1-851869949,Custom Wealth Services LLC,"OH, Columbus, 5559 Orville Avenue",US
6,S1-785847572,Consulting Nyasa Nursing Private Limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",India
7,S1-27541239,Nexus Anchor Rain,"1111 Church Street, Unit 2007, Nashville, TN",US
8,S1-629417405,Moore Bitwise Inc,"337 Oakland Avenue, Michigan City, IN",US
9,S1-22305073,Dermatology Green Medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",US

================================================================================
train_source2.tsv

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US
5,S2-138046867,Lee and Lawson,"1702 Pine Avenue, CITY OF MENOMONIE, WI",US
6,S2-584977605,SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPOR...,"H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab",India
7,S2-277444929,Shree Infracon Private Ltd,"63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKH...",India
8,S2-721031885,Chavira Platinum Chimera LLC,"282 SAXONY DRIVE, FTT MITCHELL, KY",US
9,S2-508602797,FOUNDATION EXCEL AGENCY PRIVATE LIMITED,"HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, M...",India

================================================================================
train_source3.tsv

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India
5,S3-578159284,LLC Hernandez Colonial Redwood,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...",US
6,S3-121412624,Classic Equity Partners Group,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...",US
7,S3-249416830,Ectolumdrex dba X+ Madison Inc,"S03575 Cty Tk M, Town Of Buffalo, WI",US
8,S3-107644605,Animal Hanisch Hospirlg,"##8 Willow Oak Lane, Fl. 0, Saint Louis, Missouri",US
9,S3-160217003,Gomez Optimal,"343 Hempstead 161, Hope, Arkansas",US