In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = Path.cwd()

sys.path.insert(0, str(PROJECT_ROOT))

from src.normalization import (
    normalize_business_name,
    normalize_address,
    add_normalized_columns,
)

In [2]:
test_names = [
    "ABC Technologies Pvt. Ltd.",
    "ABC Technologies Private Limited",
    "ABC TECHNOLOGIES PVT LTD",
    "Amazon.com, Inc.",
    None,
]

for name in test_names:
    print(f"{name!r} -> {normalize_business_name(name)!r}")

'ABC Technologies Pvt. Ltd.' -> 'abc technologies private limited'
'ABC Technologies Private Limited' -> 'abc technologies private limited'
'ABC TECHNOLOGIES PVT LTD' -> 'abc technologies private limited'
'Amazon.com, Inc.' -> 'amazon com incorporated'
None -> ''

In [3]:
test_addresses = [
    "12 MG Rd., Hyderabad",
    "12 MG Road, Hyderabad",
    "25 Park Ave.",
    None,
]

for address in test_addresses:
    print(f"{address!r} -> {normalize_address(address)!r}")

'12 MG Rd., Hyderabad' -> '12 mg road hyderabad'
'12 MG Road, Hyderabad' -> '12 mg road hyderabad'
'25 Park Ave.' -> '25 park avenue'
None -> ''

Test on the REAL data

In [6]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\konda\23BQ1A4223\amazon-ml-challenge-2026\student_resource\dataset\train\train_source1.tsv",
    sep="\t"
)

df = add_normalized_columns(df)

display(
    df[
        [
            "business_name",
            "business_name_normalized",
            "business_address",
            "business_address_normalized",
            "country",
            "country_normalized",
        ]
    ].head(20)
)

,business_name,business_name_normalized,business_address,business_address_normalized,country,country_normalized
0,Orelee's Barbershop,orelee s barbershop,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,US,us
1,Prime Money,prime money,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,US,us
2,B+ Retail Inc,b retail incorporated,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,US,us
3,Christ Chapel,christ chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,US,us
4,Prabhav Business Center,prabhav business center,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,India,india
5,Custom Wealth Services LLC,custom wealth services limited liability company,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue,US,us
6,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...,India,india
7,Nexus Anchor Rain,nexus anchor rain,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn,US,us
8,Moore Bitwise Inc,moore bitwise incorporated,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in,US,us
9,Dermatology Green Medicine,dermatology green medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...,US,us
10,Crystal Lending PC,crystal lending pc,"11643 Prosperity Road, South Jordan, UT",11643 prosperity road south jordan ut,US,us
11,Dream Construction Limited,dream construction limited,"H.No.16-11-23/37/A, 2Nd Floor, Flat No.207, Sa...",h no 16 11 23 37 a 2nd floor flat no 207 sagar...,India,india
12,"Kelly Advisory, Inc",kelly advisory incorporated,"301 1st Street, Chokio, MN",301 1st street chokio mn,US,us
13,Helios,helios,"66 Edgewood Street, Bridgeport, CT",66 edgewood street bridgeport court,US,us
14,Unified Choice Dynamix,unified choice dynamix,"Unit BUILDING 3030, MD, 2701 Eastern Boulevard...",unit building 3030 md 2701 eastern boulevard m...,US,us
15,Health Fellowship Partners,health fellowship partners,"601 Oleander Circle, Virginia Beach City, VA",601 oleander circle virginia beach city va,US,us
16,Smart Healthcare Private Limited,smart healthcare private limited,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",303 3rd floor sakar 5 b h natraj cinema ashram...,India,india
17,Callicoat & Dailey Inc,callicoat dailey incorporated,"Charlotte, NC, 833 Reliance Street",charlotte nc 833 reliance street,US,us
18,Iris Advisors,iris advisors,House No-777 Raghubir Bhawanmadan Pur Khadar S...,house no 777 raghubir bhawanmadan pur khadar s...,India,india
19,Secunderabad Park Private Limited,secunderabad park private limited,"Secunderabad, Hyderabad, Plot No.53, Flat No.4...",secunderabad hyderabad plot no 53 flat no 402 ...,India,india

In [7]:
df = add_normalized_columns(df)

print("Columns after normalization:")
print(df.columns.tolist())

Columns after normalization:
['entity_id', 'business_name', 'business_address', 'country', 'business_name_normalized', 'business_address_normalized', 'country_normalized']

In [8]:
display(
    df[
        [
            "business_name",
            "business_name_normalized",
            "business_address",
            "business_address_normalized",
            "country",
            "country_normalized",
        ]
    ].head(20)
)

,business_name,business_name_normalized,business_address,business_address_normalized,country,country_normalized
0,Orelee's Barbershop,orelee s barbershop,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,US,us
1,Prime Money,prime money,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,US,us
2,B+ Retail Inc,b retail incorporated,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,US,us
3,Christ Chapel,christ chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,US,us
4,Prabhav Business Center,prabhav business center,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,India,india
5,Custom Wealth Services LLC,custom wealth services limited liability company,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue,US,us
6,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...,India,india
7,Nexus Anchor Rain,nexus anchor rain,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn,US,us
8,Moore Bitwise Inc,moore bitwise incorporated,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in,US,us
9,Dermatology Green Medicine,dermatology green medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...,US,us
10,Crystal Lending PC,crystal lending pc,"11643 Prosperity Road, South Jordan, UT",11643 prosperity road south jordan ut,US,us
11,Dream Construction Limited,dream construction limited,"H.No.16-11-23/37/A, 2Nd Floor, Flat No.207, Sa...",h no 16 11 23 37 a 2nd floor flat no 207 sagar...,India,india
12,"Kelly Advisory, Inc",kelly advisory incorporated,"301 1st Street, Chokio, MN",301 1st street chokio mn,US,us
13,Helios,helios,"66 Edgewood Street, Bridgeport, CT",66 edgewood street bridgeport court,US,us
14,Unified Choice Dynamix,unified choice dynamix,"Unit BUILDING 3030, MD, 2701 Eastern Boulevard...",unit building 3030 md 2701 eastern boulevard m...,US,us
15,Health Fellowship Partners,health fellowship partners,"601 Oleander Circle, Virginia Beach City, VA",601 oleander circle virginia beach city va,US,us
16,Smart Healthcare Private Limited,smart healthcare private limited,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",303 3rd floor sakar 5 b h natraj cinema ashram...,India,india
17,Callicoat & Dailey Inc,callicoat dailey incorporated,"Charlotte, NC, 833 Reliance Street",charlotte nc 833 reliance street,US,us
18,Iris Advisors,iris advisors,House No-777 Raghubir Bhawanmadan Pur Khadar S...,house no 777 raghubir bhawanmadan pur khadar s...,India,india
19,Secunderabad Park Private Limited,secunderabad park private limited,"Secunderabad, Hyderabad, Plot No.53, Flat No.4...",secunderabad hyderabad plot no 53 flat no 402 ...,India,india

In [9]:
original_name = df["business_name"].fillna("").astype(str)
normalized_name = df["business_name_normalized"]

original_address = df["business_address"].fillna("").astype(str)
normalized_address = df["business_address_normalized"]

name_changed = original_name != normalized_name
address_changed = original_address != normalized_address

print(
    "Business names changed:",
    name_changed.sum(),
    "/",
    len(df)
)

print(
    "Addresses changed:",
    address_changed.sum(),
    "/",
    len(df)
)

Business names changed: 2206821 / 2206821
Addresses changed: 2206821 / 2206821

In [10]:
display(
    df.loc[
        name_changed,
        [
            "business_name",
            "business_name_normalized"
        ]
    ].head(30)
)

,business_name,business_name_normalized
0,Orelee's Barbershop,orelee s barbershop
1,Prime Money,prime money
2,B+ Retail Inc,b retail incorporated
3,Christ Chapel,christ chapel
4,Prabhav Business Center,prabhav business center
5,Custom Wealth Services LLC,custom wealth services limited liability company
6,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited
7,Nexus Anchor Rain,nexus anchor rain
8,Moore Bitwise Inc,moore bitwise incorporated
9,Dermatology Green Medicine,dermatology green medicine
10,Crystal Lending PC,crystal lending pc
11,Dream Construction Limited,dream construction limited
12,"Kelly Advisory, Inc",kelly advisory incorporated
13,Helios,helios
14,Unified Choice Dynamix,unified choice dynamix
15,Health Fellowship Partners,health fellowship partners
16,Smart Healthcare Private Limited,smart healthcare private limited
17,Callicoat & Dailey Inc,callicoat dailey incorporated
18,Iris Advisors,iris advisors
19,Secunderabad Park Private Limited,secunderabad park private limited
20,Holy Synagogue,holy synagogue
21,Green Logistics Private Limited,green logistics private limited
22,Scott Eagle Inc,scott eagle incorporated
23,Rajani Enterprises of Kannur,rajani enterprises of kannur
24,"Schaefer, Michael and Silver Associates",schaefer michael and silver associates
25,Colline Molitor Sea LLC,colline molitor sea limited liability company
26,"Aggie E. Nagle, L.C.S.W.",aggie e nagle l c s w
27,Angad Multitrade Ltd,angad multitrade limited
28,Global Hovnanian LLC,global hovnanian limited liability company
29,Pacific Learning Laboratories LLC,pacific learning laboratories limited liabilit...

In [11]:
display(
    df.loc[
        address_changed,
        [
            "business_address",
            "business_address_normalized"
        ]
    ].head(30)
)

,business_address,business_address_normalized
0,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc
1,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok
2,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az
3,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md
4,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal
5,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue
6,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...
7,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn
8,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in
9,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...
10,"11643 Prosperity Road, South Jordan, UT",11643 prosperity road south jordan ut
11,"H.No.16-11-23/37/A, 2Nd Floor, Flat No.207, Sa...",h no 16 11 23 37 a 2nd floor flat no 207 sagar...
12,"301 1st Street, Chokio, MN",301 1st street chokio mn
13,"66 Edgewood Street, Bridgeport, CT",66 edgewood street bridgeport court
14,"Unit BUILDING 3030, MD, 2701 Eastern Boulevard...",unit building 3030 md 2701 eastern boulevard m...
15,"601 Oleander Circle, Virginia Beach City, VA",601 oleander circle virginia beach city va
16,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",303 3rd floor sakar 5 b h natraj cinema ashram...
17,"Charlotte, NC, 833 Reliance Street",charlotte nc 833 reliance street
18,House No-777 Raghubir Bhawanmadan Pur Khadar S...,house no 777 raghubir bhawanmadan pur khadar s...
19,"Secunderabad, Hyderabad, Plot No.53, Flat No.4...",secunderabad hyderabad plot no 53 flat no 402 ...
20,"Sapulpa, OK, 2204 Park Street",sapulpa ok 2204 park street
21,"E-7, Second Floor, New Delhi, South Delhi, Delhi",e 7 second floor new delhi south delhi delhi
22,"4828 Hedges Avenue, Kansas City, MO",4828 hedges avenue kansas city mo
23,"46/1106, Dhanalakshmi Road, Near Amani Auditor...",46 1106 dhanalakshmi road near amani auditoriu...
24,"32876 Circle Drive, Millsboro, DE",32876 circle drive millsboro de
25,"5620 Trinity Road, Unit 103, Raleigh, NC",5620 trinity road unit 103 raleigh nc
26,"11900 54th Avenue, Plymouth, MN",11900 54th avenue plymouth mn
27,"Building No. 37/4, First Floor Opp Bharata Mat...",building no 37 4 first floor opp bharata mata ...
28,"4024 39th Avenue, Seattle, WA",4024 39th avenue seattle wa
29,"4810 Nassau Avenue, Sand Springs, OK",4810 nassau avenue sand springs ok

In [12]:
print("Empty original business names:",
      (df["business_name"].fillna("").astype(str).str.strip() == "").sum())

print("Empty normalized business names:",
      (df["business_name_normalized"].str.strip() == "").sum())

print()

print("Empty original addresses:",
      (df["business_address"].fillna("").astype(str).str.strip() == "").sum())

print("Empty normalized addresses:",
      (df["business_address_normalized"].str.strip() == "").sum())

Empty original business names: 0
Empty normalized business names: 0

Empty original addresses: 0
Empty normalized addresses: 0

In [13]:
print("Original countries:")
print(df["country"].value_counts(dropna=False))

print("\nNormalized countries:")
print(df["country_normalized"].value_counts(dropna=False))

Original countries:
country
US       1323633
India     883188
Name: count, dtype: int64

Normalized countries:
country_normalized
us       1323633
india     883188
Name: count, dtype: int64

In [14]:
name_counts = (
    df["business_name_normalized"]
    .value_counts()
)

print("Unique normalized business names:",
      name_counts.size)

print("Total rows:",
      len(df))

print("\nMost common normalized names:")

display(
    name_counts
    .head(20)
    .to_frame("count")
)

Unique normalized business names: 1504001
Total rows: 2206821

Most common normalized names:

                           count
business_name_normalized
primary care group           253
ear nose throat group        251
pediatric group              222
womens health group          220
physical therapy group       218
pediatric dental group       216
behavioral health group      215
chiropractic group           209
orthopedic group             208
eye group                    207
dental group                 205
family group                 204
dermatology group            202
vision group                 199
urgent care group            198
pediatric dentistry group    198
internal medicine group      197
foot ankle group             191
oncology group               188
urology group                185

In [15]:
unique_name_rows = (
    df["business_name_normalized"]
    .value_counts()
)

print(
    "Names appearing exactly once:",
    (unique_name_rows == 1).sum()
)

print(
    "Names appearing more than once:",
    (unique_name_rows > 1).sum()
)

print(
    "Maximum frequency of one normalized name:",
    unique_name_rows.max()
)

Names appearing exactly once: 1323234
Names appearing more than once: 180767
Maximum frequency of one normalized name: 253

In [16]:
original_name = df["business_name"].fillna("").astype(str)
normalized_name = df["business_name_normalized"]

name_changed = original_name != normalized_name

print(
    "Business names changed:",
    name_changed.sum(),
    "/",
    len(df)
)

display(
    df.loc[
        name_changed,
        [
            "business_name",
            "business_name_normalized"
        ]
    ].head(30)
)

Business names changed: 2206821 / 2206821

,business_name,business_name_normalized
0,Orelee's Barbershop,orelee s barbershop
1,Prime Money,prime money
2,B+ Retail Inc,b retail incorporated
3,Christ Chapel,christ chapel
4,Prabhav Business Center,prabhav business center
5,Custom Wealth Services LLC,custom wealth services limited liability company
6,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited
7,Nexus Anchor Rain,nexus anchor rain
8,Moore Bitwise Inc,moore bitwise incorporated
9,Dermatology Green Medicine,dermatology green medicine
10,Crystal Lending PC,crystal lending pc
11,Dream Construction Limited,dream construction limited
12,"Kelly Advisory, Inc",kelly advisory incorporated
13,Helios,helios
14,Unified Choice Dynamix,unified choice dynamix
15,Health Fellowship Partners,health fellowship partners
16,Smart Healthcare Private Limited,smart healthcare private limited
17,Callicoat & Dailey Inc,callicoat dailey incorporated
18,Iris Advisors,iris advisors
19,Secunderabad Park Private Limited,secunderabad park private limited
20,Holy Synagogue,holy synagogue
21,Green Logistics Private Limited,green logistics private limited
22,Scott Eagle Inc,scott eagle incorporated
23,Rajani Enterprises of Kannur,rajani enterprises of kannur
24,"Schaefer, Michael and Silver Associates",schaefer michael and silver associates
25,Colline Molitor Sea LLC,colline molitor sea limited liability company
26,"Aggie E. Nagle, L.C.S.W.",aggie e nagle l c s w
27,Angad Multitrade Ltd,angad multitrade limited
28,Global Hovnanian LLC,global hovnanian limited liability company
29,Pacific Learning Laboratories LLC,pacific learning laboratories limited liabilit...

In [17]:
original_address = df["business_address"].fillna("").astype(str)
normalized_address = df["business_address_normalized"]

address_changed = original_address != normalized_address

print(
    "Addresses changed:",
    address_changed.sum(),
    "/",
    len(df)
)

display(
    df.loc[
        address_changed,
        [
            "business_address",
            "business_address_normalized"
        ]
    ].head(30)
)

Addresses changed: 2206821 / 2206821

,business_address,business_address_normalized
0,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc
1,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok
2,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az
3,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md
4,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal
5,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue
6,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...
7,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn
8,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in
9,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...
10,"11643 Prosperity Road, South Jordan, UT",11643 prosperity road south jordan ut
11,"H.No.16-11-23/37/A, 2Nd Floor, Flat No.207, Sa...",h no 16 11 23 37 a 2nd floor flat no 207 sagar...
12,"301 1st Street, Chokio, MN",301 1st street chokio mn
13,"66 Edgewood Street, Bridgeport, CT",66 edgewood street bridgeport court
14,"Unit BUILDING 3030, MD, 2701 Eastern Boulevard...",unit building 3030 md 2701 eastern boulevard m...
15,"601 Oleander Circle, Virginia Beach City, VA",601 oleander circle virginia beach city va
16,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",303 3rd floor sakar 5 b h natraj cinema ashram...
17,"Charlotte, NC, 833 Reliance Street",charlotte nc 833 reliance street
18,House No-777 Raghubir Bhawanmadan Pur Khadar S...,house no 777 raghubir bhawanmadan pur khadar s...
19,"Secunderabad, Hyderabad, Plot No.53, Flat No.4...",secunderabad hyderabad plot no 53 flat no 402 ...
20,"Sapulpa, OK, 2204 Park Street",sapulpa ok 2204 park street
21,"E-7, Second Floor, New Delhi, South Delhi, Delhi",e 7 second floor new delhi south delhi delhi
22,"4828 Hedges Avenue, Kansas City, MO",4828 hedges avenue kansas city mo
23,"46/1106, Dhanalakshmi Road, Near Amani Auditor...",46 1106 dhanalakshmi road near amani auditoriu...
24,"32876 Circle Drive, Millsboro, DE",32876 circle drive millsboro de
25,"5620 Trinity Road, Unit 103, Raleigh, NC",5620 trinity road unit 103 raleigh nc
26,"11900 54th Avenue, Plymouth, MN",11900 54th avenue plymouth mn
27,"Building No. 37/4, First Floor Opp Bharata Mat...",building no 37 4 first floor opp bharata mata ...
28,"4024 39th Avenue, Seattle, WA",4024 39th avenue seattle wa
29,"4810 Nassau Avenue, Sand Springs, OK",4810 nassau avenue sand springs ok

In [18]:
name_counts = df["business_name_normalized"].value_counts()

print("Total rows:", len(df))
print("Unique normalized names:", len(name_counts))

print(
    "\nNames appearing exactly once:",
    (name_counts == 1).sum()
)

print(
    "Names appearing more than once:",
    (name_counts > 1).sum()
)

print(
    "Maximum frequency of one normalized name:",
    name_counts.max()
)

print("\nMost common normalized names:")

display(
    name_counts
    .head(20)
    .to_frame("count")
)

Total rows: 2206821
Unique normalized names: 1504001

Names appearing exactly once: 1323234
Names appearing more than once: 180767
Maximum frequency of one normalized name: 253

Most common normalized names:

                           count
business_name_normalized
primary care group           253
ear nose throat group        251
pediatric group              222
womens health group          220
physical therapy group       218
pediatric dental group       216
behavioral health group      215
chiropractic group           209
orthopedic group             208
eye group                    207
dental group                 205
family group                 204
dermatology group            202
vision group                 199
urgent care group            198
pediatric dentistry group    198
internal medicine group      197
foot ankle group             191
oncology group               188
urology group                185

In [19]:
print("Original countries:")
print(df["country"].value_counts(dropna=False))

print("\nNormalized countries:")
print(df["country_normalized"].value_counts(dropna=False))

Original countries:
country
US       1323633
India     883188
Name: count, dtype: int64

Normalized countries:
country_normalized
us       1323633
india     883188
Name: count, dtype: int64